version: '3.8'

services:
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: frontendDocker
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - shared-network

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: backendDocker
    ports:
      - "8080:8080"
    volumes:
      - ./Server:/app
    depends_on:
      - db
    networks:
      - shared-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05022001
      POSTGRES_DB: restaurant_management
    container_name: dbDocker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
      - db
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge

volumes:
  postgres-data:
